import type { CredentialFull, CredentialSummary, ScoreBreakdown } from "../types";

export const NOW = Date.now();
export const DAY = 24 * 60 * 60 * 1000;

/** 테스트용 기본 score — safe/100 */
export const MOCK_SAFE_SCORE: ScoreBreakdown = {
  total: 100,
  level: "safe",
  factors: [],
};

/** 테스트용 mock credential 10개 — 다양한 env/status/expires_at 조합 */
export const MOCK_CREDENTIALS: CredentialSummary[] = [
  {
    id: "01HZAAAAAAAAAAAAAAAAAAAAAA",
    issuer_id: "01HZBBBBBBBBBBBBBBBBBBBBBB",
    name: "OpenAI API Key",
    env: "prod",
    status: "active",
    expires_at: NOW + 60 * DAY,
    hash_hint: "aaaa",
    score: MOCK_SAFE_SCORE,
    kind: "api_key",
    url: null,
    username: null,
    has_secondary: false,
    primary_label: null,
    secondary_label: null,
  },
  {
    id: "01HZAAAAAAAAAAAAAAAAAAAAAB",
    issuer_id: "01HZBBBBBBBBBBBBBBBBBBBBBC",
    name: "Stripe Secret Key",
    env: "prod",
    status: "active",
    expires_at: NOW + 10 * DAY, // expiring soon
    hash_hint: null,
    score: {
      total: 80,
      level: "safe",
      factors: [{ code: "expiring_soon", severity: "warn", penalty: 20, days: 10 }],
    },
    kind: "api_key",
    url: null,
    username: null,
    has_secondary: false,
    primary_label: null,
    secondary_label: null,
  },
  {
    id: "01HZAAAAAAAAAAAAAAAAAAAAAC",
    issuer_id: "01HZBBBBBBBBBBBBBBBBBBBBBD",
    name: "GitHub Token Dev",
    env: "dev",
    status: "active",
    expires_at: null,
    hash_hint: null,
    score: MOCK_SAFE_SCORE,
    kind: "api_key",
    url: null,
    username: null,
    has_secondary: false,
    primary_label: null,
    secondary_label: null,
  },
  {
    id: "01HZAAAAAAAAAAAAAAAAAAAAAD",
    issuer_id: "01HZBBBBBBBBBBBBBBBBBBBBBB",
    name: "Vercel Deploy Token",
    env: "staging",
    status: "active",
    expires_at: NOW - 5 * DAY, // expired
    hash_hint: null,
    score: {
      total: 50,
      level: "warn",
      factors: [{ code: "expired", severity: "danger", penalty: 50, days: 5 }],
    },
    kind: "api_key",
    url: null,
    username: null,
    has_secondary: false,
    primary_label: null,
    secondary_label: null,
  },
  {
    id: "01HZAAAAAAAAAAAAAAAAAAAAAE",
    issuer_id: "01HZBBBBBBBBBBBBBBBBBBBBBC",
    name: "AWS Access Key",
    env: "prod",
    status: "revoked",
    expires_at: null,
    hash_hint: null,
    score: {
      total: 0,
      level: "danger",
      factors: [{ code: "revoked", severity: "danger", penalty: 100, days: null }],
    },
    kind: "api_key",
    url: null,
    username: null,
    has_secondary: false,
    primary_label: null,
    secondary_label: null,
  },
  {
    id: "01HZAAAAAAAAAAAAAAAAAAAAAF",
    issuer_id: "01HZBBBBBBBBBBBBBBBBBBBBBD",
    name: "Supabase Service Key",
    env: "dev",
    status: "active",
    expires_at: NOW + 90 * DAY,
    hash_hint: null,
    score: MOCK_SAFE_SCORE,
    kind: "api_key",
    url: null,
    username: null,
    has_secondary: false,
    primary_label: null,
    secondary_label: null,
  },
  {
    id: "01HZAAAAAAAAAAAAAAAAAAAAAG",
    issuer_id: "01HZBBBBBBBBBBBBBBBBBBBBBB",
    name: "SendGrid API Key",
    env: "staging",
    status: "compromised",
    expires_at: null,
    hash_hint: null,
    score: {
      total: 0,
      level: "danger",
      factors: [{ code: "compromised", severity: "danger", penalty: 100, days: null }],
    },
    kind: "api_key",
    url: null,
    username: null,
    has_secondary: false,
    primary_label: null,
    secondary_label: null,
  },
  {
    id: "01HZAAAAAAAAAAAAAAAAAAAAAH",
    issuer_id: "01HZBBBBBBBBBBBBBBBBBBBBBC",
    name: "Twilio Auth Token",
    env: "prod",
    status: "active",
    expires_at: NOW + 20 * DAY, // expiring soon
    hash_hint: null,
    score: {
      total: 80,
      level: "safe",
      factors: [{ code: "expiring_soon", severity: "warn", penalty: 20, days: 20 }],
    },
    kind: "api_key",
    url: null,
    username: null,
    has_secondary: false,
    primary_label: null,
    secondary_label: null,
  },
  {
    id: "01HZAAAAAAAAAAAAAAAAAAAAAI",
    issuer_id: "01HZBBBBBBBBBBBBBBBBBBBBBD",
    name: "Cloudflare API Key",
    env: "dev",
    status: "revoked",
    expires_at: null,
    hash_hint: null,
    score: {
      total: 0,
      level: "danger",
      factors: [{ code: "revoked", severity: "danger", penalty: 100, days: null }],
    },
    kind: "api_key",
    url: null,
    username: null,
    has_secondary: false,
    primary_label: null,
    secondary_label: null,
  },
  {
    id: "01HZAAAAAAAAAAAAAAAAAAAAAJ",
    issuer_id: "01HZBBBBBBBBBBBBBBBBBBBBBB",
    name: "Doppler Token",
    env: "staging",
    status: "active",
    expires_at: NOW + 120 * DAY,
    hash_hint: null,
    score: MOCK_SAFE_SCORE,
    kind: "api_key",
    url: null,
    username: null,
    has_secondary: false,
    primary_label: null,
    secondary_label: null,
  },
];

/** T027 테스트용 CredentialFull 픽스처 */
export const MOCK_CREDENTIAL_FULL: CredentialFull = {
  id: "01HZAAAAAAAAAAAAAAAAAAAAAA",
  issuer_id: "01HZBBBBBBBBBBBBBBBBBBBBBB",
  name: "OpenAI API Key",
  env: "prod",
  scope: "billing:read",
  vault_ref: "credentials/01HZAAAAAAAAAAAAAAAAAAAAAA",
  created_at: NOW - 30 * DAY,
  last_rotated_at: NOW - 7 * DAY,
  expires_at: NOW + 60 * DAY,
  owner: null,
  rotation_policy_days: 90,
  rotation_runbook_id: null,
  status: "active",
  hash_hint: "abc1",
  usages: [],
  score: MOCK_SAFE_SCORE,
  kind: "api_key",
  url: null,
  username: null,
  secondary_value_ref: null,
  primary_label: null,
  secondary_label: null,
};
