pub mod audit;
pub mod auth;
pub mod charter_cooldown;
pub mod credentials;
pub mod credit_card;
pub mod deployments;
pub mod entitlement;
pub mod ext_pairing;
pub mod extension_session;
pub mod github;
pub mod graph;
pub mod import;
pub mod incidents;
pub mod issuer;
pub mod issuer_recipe;
pub mod kill_switch;
pub mod pairing;
pub mod projects;
pub mod railguard;
pub mod scanner;
pub mod security_check;
pub mod settings;
pub mod supply;
pub mod sync;
pub mod usage;
pub mod vault;
pub mod vault_settings;

// 클립보드 커맨드는 tauri-plugin-clipboard-manager 가 활성화된 빌드에서만 컴파일
#[cfg(feature = "tauri-plugins")]
pub mod clipboard;
